package com.somersbmatthews;

/**
 * Hello world!
 *
 */
public class App {
    public static void main(String[] args) {
        int result = triangleSeries();
        System.out.println("the first triangle series number with 500 divisors");
        System.out.println(result);
        // solution is 63190
    }

    private static int triangleSeries() {
        int j = 1, k = 1;
        while (true) {
            int numberOfDivisors = factorWhile(k);
            if (numberOfDivisors > 500) {
                return k;
            }
            j = j + 1;
            k = k + j;
        }
    }

    private static int factorWhile(int num) {
        int count = 0;

        for (int i = 1; i <= Math.sqrt(num); i++) {
            if (num % 1 == 0) {
                count++;
                if (i != num / i) {
                    count++;
                }
            }
        }
        return count;
    }
}

// The sequence
// of triangle
// numbers is
// generated by
// adding the
// natural numbers.
// So the7th
// triangle number
// would be 1+2+3+4+5+6+7=28.
// The first
// ten terms
// would be:1,3,6,10,15,21,28,36,45,55,...
// Let us
// list the
// factors of
// the first
// seven triangle numbers:1:1 3:1,3 6:1,2,3,6 10:1,2,5,10 15:1,3,5,15
// 21:1,3,7,21 28:1,2,4,7,14,28
// We can
// see that 28
// is the
// first triangle
// number to
// have over
// five divisors.
// What is
// the value
// of the
// first triangle
// number to
// have over
// five hundred divisors
// ?
